server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/carpool_auth
    username: root
    password: "@Harsh007"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: harshiitsonii@gmail.com
    password: xuqhjwwwaetknadm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


jwt:
  secret: "qwertyuiopasdfghjklzxcvbnmqwertyuiop"
  expiration: 86400000
