server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                        - Path=/auth/**

            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/employee/**, /notifications/**, /vehicle/**

            - id: ride-service
              uri: lb://ride-service
              predicates:
                        - Path=/ride/**, /locations

            - id: ride-service-ws-direct
              uri: lb://ride-service
              predicates:
                - Path=/ws/**

            - id: ride-service-ws-api
              uri: lb://ride-service
              predicates:
                - Path=/api/ws/**
              filters:
                - StripPrefix=1

            - id: admin-service
              uri: lb://admin-service
              predicates:
                        - Path=/admin/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
jwt:
  secret: "qwertyuiopasdfghjklzxcvbnmqwertyuiop"
