server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                        - Path=/auth/**

            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/employee/**, /notifications/**, /vehicle/**

            - id: ride-service
              uri: lb://ride-service
              predicates:
                        - Path=/ride/**, /locations

            - id: ride-service-ws-direct
              uri: lb://ride-service
              predicates:
                - Path=/ws/**

            - id: ride-service-ws-api
              uri: lb://ride-service
              predicates:
                - Path=/api/ws/**
              filters:
                - StripPrefix=1

            - id: admin-service
              uri: lb://admin-service
              predicates:
                        - Path=/admin/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

# CORS Configuration for Frontend Integration
cors:
  allowed-origins: "http://localhost:*,https://localhost:*,https://salmon-sand-087aeff00.1.azurestaticapps.net,https://*.azurestaticapps.net,https://*.azurewebsites.net,https://*.vercel.app,https://*.netlify.app,https://*.github.io"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized

logging:
  level:
    org.springframework.cloud.gateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
