server:
  port: 8082

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/carpool_employee
    username: root
    password: "@Harsh007"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: employee-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.orangemantra.employeeservice.messaging.NotificationEvent
        spring.json.trusted.packages: "*"
    topic:
      notifications: notifications

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: "qwertyuiopasdfghjklzxcvbnmqwertyuiop"
