name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  RESOURCE_GROUP: rg-cubicleride

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Services
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Run Tests
      run: mvn clean test -B
      
    - name: Generate Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: '**/target/surefire-reports/*.xml'
        reporter: java-junit

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    name: Build and Push Images
    
    strategy:
      matrix:
        service: [eureka-server, api-gateway, auth-service, employee-service, ride-service, admin-service]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build JAR for ${{ matrix.service }}
      run: mvn clean package -pl ${{ matrix.service }} -am -DskipTests -B
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}
    
    - name: Build and Push Docker Image
      run: |
        cd ${{ matrix.service }}
        docker build -t ${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }} .
        docker push ${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }}
        docker tag ${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ matrix.service }}:latest
        docker push ${{ env.REGISTRY }}/${{ matrix.service }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    name: Deploy to Azure Container Apps
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Services
      run: |
        services=("eureka-server" "api-gateway" "auth-service" "employee-service" "ride-service" "admin-service")
        for service in "${services[@]}"; do
          az containerapp update \
            --name $service \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY }}/$service:${{ github.sha }}
        done
